const WA='201119295523';let products=[];let cart=JSON.parse(localStorage.getItem('elkheshenCart')||'[]');let currentFilter='all';const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const js=v=>String(v??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'");
async function load(){try{const r=await fetch('/api/products',{cache:'no-store'});if(!r.ok)throw new Error(`API ${r.status}`);products=await r.json();render()}catch(e){$('#productsGrid').innerHTML='<div class="empty">تعذر تحميل السيارات حاليًا. حاول تحديث الصفحة.</div>'}}
function imgs(p){return Array.isArray(p.images)&&p.images.length?p.images.filter(Boolean):[p.image].filter(Boolean)}
function category(p){const s=(p.category||p.type||p.name||'').toLowerCase();if(/suv|jeep|تويوتا راش|سبورتاج|توسان|كريتا|كابتيفا/.test(s))return'suv';if(/sedan|سيدان|e200|c200|النترا|صني|لوجان|bmw 3|a6/.test(s))return'sedan';return'other'}
function render(){const list=currentFilter==='all'?products:products.filter(p=>category(p)===currentFilter);$('#productsGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">لا توجد سيارات في هذا التصنيف حاليًا.</div>'}
function card(p){const pic=imgs(p)[0]||'';const sold=p.status==='sold';return `<article class="car-card ${sold?'sold':''}" onclick="openProduct('${js(p.id)}')" style="cursor:pointer"><div class="car-image">${pic?`<img src="${esc(pic)}" alt="${esc(p.name)}" onerror="this.style.display='none'">`:''}${sold?'<div class="sold-overlay"><span>مبــــاع</span></div>':''}<button class="heart" onclick="event.stopPropagation();openProduct('${js(p.id)}')" aria-label="التفاصيل">↗</button>${p.badge?`<span class="car-badge">${esc(p.badge)}</span>`:''}</div><div class="car-body"><div class="car-title"><h3>${esc(p.name)}</h3><span class="year">${esc(p.year||'—')}</span></div><div class="specs"><span class="spec">⚙ ${esc(p.transmission||'أوتوماتيك')}</span><span class="spec">⛽ ${esc(p.fuel||'بنزين')}</span><span class="spec">🛣 ${Number(p.mileage||0).toLocaleString('ar-EG')} كم</span></div><div class="car-price">${Number(p.price||0).toLocaleString('ar-EG')} ج.م</div><div class="car-actions"><button class="btn ${sold?'sold-btn':'btn-primary'}" ${sold?'disabled':''} onclick="event.stopPropagation();${sold?'return false':`add('${js(p.id)}')`}">${sold?'السيارة مباعة':'أضف للسلة 🛒'}</button><button class="icon-action" onclick="event.stopPropagation();openProduct('${js(p.id)}')" aria-label="عرض التفاصيل">↗</button></div></div></article>`}
function openCart(){$('#cartModal').classList.remove('hidden');renderCart()}function renderCart(){const box=$('#cartItems');if(!cart.length){box.innerHTML='<div class="empty">السلة فارغة. اختار سيارة وأضفها للسلة.</div>';$('#cartTotal').textContent='0';return}box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return'';const pic=imgs(p)[0]||'';return `<div class="cart-row"><img class="cart-thumb" src="${esc(pic)}" alt=""><div class="cart-product-info"><b>${esc(p.name)}</b><br><small>${Number(p.price||0).toLocaleString('ar-EG')} ج.م</small></div><div class="qty"><button onclick="changeQty('${js(i.id)}',-1)">−</button>${i.qty}<button onclick="changeQty('${js(i.id)}',1)">+</button></div></div>`}).join('');$('#cartTotal').textContent=cart.reduce((n,i)=>n+i.qty,0)}
function changeQty(id,d){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);save();renderCart()}
function openProduct(id){if(!id)return;window.location.href='/car.html?id='+encodeURIComponent(id)}
function showDetailImage(i){const m=$('#productModal'),list=JSON.parse(m.dataset.images||'[]');if(list[i])$('#detailMainImg').src=list[i];document.querySelectorAll('.detail-thumb').forEach((b,n)=>b.classList.toggle('active',n===i))}function closeProduct(){$('#productModal').classList.add('hidden')}
$('#cartBtn').onclick=openCart;$('#checkoutBtn').onclick=()=>{if(!cart.length)return alert('السلة فارغة');$('#cartModal').classList.add('hidden');$('#orderModal').classList.remove('hidden')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));$('#orderForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const lines=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `• ${p?.name||i.id} × ${i.qty}`}).join('\n');const msg=`مرحبًا، أريد الاستفسار عن السيارات التالية من Automobile Elkheshen.\n\n${lines}\n\nالاسم: ${f.get('customer')}\nالهاتف: ${f.get('phone')}\nالعنوان: ${f.get('address')}\nملاحظات: ${f.get('note')||'لا يوجد'}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank');cart=[];save();e.target.reset();$('#orderModal').classList.add('hidden')};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});$('#mobileMenu').onclick=()=>$('#mainNav').classList.toggle('open');document.querySelectorAll('#mainNav a').forEach(a=>a.onclick=()=>$('#mainNav').classList.remove('open'));updateCount();load();

const sellModal=$('#sellModal');$('#openSellModal').onclick=()=>sellModal.classList.remove('hidden');$('#sellImages').addEventListener('change',e=>{const f=[...e.target.files];$('#sellStatus').textContent=f.length>8?'يمكن اختيار 8 صور كحد أقصى.':f.some(x=>x.size>2*1024*1024)?'حجم كل صورة يجب ألا يتجاوز 2 ميجابايت.':`${f.length} صورة جاهزة للرفع.`});$('#sellForm').onsubmit=async e=>{e.preventDefault();const files=[...$('#sellImages').files],status=$('#sellStatus'),btn=e.target.querySelector('button[type=submit]');if(!files.length){status.textContent='من فضلك أضف صورة واحدة على الأقل.';return}if(files.length>8||files.some(f=>f.size>2*1024*1024)){status.textContent='راجع عدد الصور وحجمها.';return}btn.disabled=true;btn.textContent='جاري الإرسال...';try{const fd=new FormData(e.target);files.forEach(f=>fd.append('images',f));const r=await fetch('/api/car-submissions',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر إرسال الإعلان');status.textContent='تم إرسال السيارة للمراجعة. هتظهر على الموقع بعد موافقة الإدارة.';e.target.reset();setTimeout(()=>sellModal.classList.add('hidden'),1800)}catch(err){status.textContent=err.message||'حدث خطأ أثناء الإرسال.'}finally{btn.disabled=false;btn.textContent='إرسال للمراجعة'}};

// Public staff portal: permissions are assigned by the primary admin.
(function(){
const tokenKey='elk_staff_token', userKey='elk_staff_user'; let staffToken=sessionStorage.getItem(tokenKey)||''; let staffUser=JSON.parse(sessionStorage.getItem(userKey)||'null');
const q=s=>document.querySelector(s), modal=q('#staffModal'); if(!modal)return;
const esc2=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function perms(){const p=staffUser?.permissions||{};return{publish:p.publish!==false,edit:!!p.edit,delete:!!p.delete,approve:!!p.approve}}
function staffApi(url,opt={}){const headers={...(opt.headers||{})};if(staffToken)headers.Authorization='Bearer '+staffToken;return fetch(url,{...opt,headers}).then(async r=>{let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(Error(d.error||'تعذر تنفيذ الطلب'),{status:r.status});return d})}
function openStaff(){modal.classList.remove('hidden');if(staffToken){showStaff()}else{q('#staffLoginBox').classList.remove('hidden');q('#staffPanel').classList.add('hidden')}}
async function showStaff(){q('#staffLoginBox').classList.add('hidden');q('#staffPanel').classList.remove('hidden');try{if(staffToken){const fresh=await staffApi('/api/staff/me');if(fresh?.user){staffUser=fresh.user;sessionStorage.setItem(userKey,JSON.stringify(staffUser));}}}catch(e){}q('#staffName').textContent=staffUser?.name||staffUser?.email||'فريق المعرض';applyPermissions();if(perms().publish||perms().edit||perms().delete)loadStaffAds();if(perms().approve)loadStaffSubmissions()}
function applyPermissions(){const p=perms();const form=q('#staffProductForm'),list=q('#staffAdsList'),sub=q('#staffSubmissionsList');if(form)form.classList.toggle('hidden',!p.publish);const head=document.querySelector('.staff-list-head');if(head)head.classList.toggle('hidden',!p.publish);if(list)list.classList.toggle('hidden',!p.publish);if(sub)sub.closest('.staff-submissions')?.classList.toggle('hidden',!p.approve);}
function closeStaff(){modal.classList.add('hidden')}
q('#staffAccess').onclick=()=>openStaff(); q('#staffLogout').onclick=()=>{staffToken='';staffUser=null;sessionStorage.removeItem(tokenKey);sessionStorage.removeItem(userKey);q('#staffPanel').classList.add('hidden');q('#staffLoginBox').classList.remove('hidden');q('#staffEmail').value='';q('#staffPass').value='';};
q('#staffLoginBtn').onclick=async()=>{const email=q('#staffEmail').value.trim(),password=q('#staffPass').value;const st=q('#staffLoginStatus');if(!email||!password){st.textContent='اكتب البريد الإلكتروني وكلمة المرور.';return}const b=q('#staffLoginBtn');b.disabled=true;b.textContent='جاري الدخول...';try{const d=await staffApi('/api/staff/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});staffToken=d.token;staffUser=d.user;sessionStorage.setItem(tokenKey,staffToken);sessionStorage.setItem(userKey,JSON.stringify(staffUser));st.textContent='تم تسجيل الدخول.';showStaff()}catch(e){st.textContent=e.message}finally{b.disabled=false;b.textContent='دخول'}};
q('#staffPass').addEventListener('keydown',e=>{if(e.key==='Enter')q('#staffLoginBtn').click()});
let staffImages=[]; q('#staffImages').addEventListener('change',async e=>{const files=[...e.target.files];if(!perms().publish)return;if(files.length>12||files.some(f=>f.size>2*1024*1024)){q('#staffStatus').textContent='حتى 12 صورة، وحجم كل صورة 2MB كحد أقصى.';return}if(!files.length)return;const st=q('#staffStatus');st.textContent='جاري رفع الصور...';try{const fd=new FormData();files.forEach(f=>fd.append('images',f));const d=await staffApi('/api/admin/upload-images',{method:'POST',body:fd});staffImages.push(...(d.urls||[]));q('#staffProductForm').elements.images.value=staffImages.join('\n');renderStaffPreview();st.textContent=`تم رفع ${d.urls?.length||0} صورة.`}catch(err){st.textContent=err.message}e.target.value=''});
function renderStaffPreview(){q('#staffPreview').innerHTML=staffImages.map(x=>`<img src="${esc2(x)}" alt="">`).join('')}
function resetStaffForm(){const f=q('#staffProductForm');f.reset();f.elements.id.value='';f.elements.status.value='available';staffImages=[];renderStaffPreview();q('#staffStatus').textContent='';q('#staffSaveBtn').textContent='نشر الإعلان مباشرة'}
q('#staffProductForm').onsubmit=async e=>{e.preventDefault();const p=perms();if(!p.publish){q('#staffStatus').textContent='هذا الحساب لا يملك صلاحية النشر.';return}const b=q('#staffSaveBtn'),f=e.target;const fd=new FormData(f);fd.set('images',staffImages.join('\n'));if(!staffImages.length){q('#staffStatus').textContent='أضف صورة واحدة على الأقل.';return}b.disabled=true;b.textContent='جاري النشر...';try{const isEdit=!!f.elements.id.value;if(isEdit&&!p.edit)throw Error('هذا الحساب لا يملك صلاحية التعديل.');await staffApi('/api/admin/products',{method:'POST',body:fd});q('#staffStatus').textContent=isEdit?'تم حفظ التعديلات.':'تم نشر الإعلان مباشرة على الموقع.';resetStaffForm();await loadStaffAds();load()}catch(e){q('#staffStatus').textContent=e.message}finally{b.disabled=false;b.textContent='نشر الإعلان مباشرة'}};
async function loadStaffAds(){if(!perms().publish)return;const box=q('#staffAdsList');box.innerHTML='<div class="loading">جاري تحميل الإعلانات...</div>';try{const items=await staffApi('/api/admin/products');box.innerHTML=items.map(p=>{const canEdit=perms().edit,canDelete=perms().delete;return `<div class="staff-ad-row"><img src="${esc2((p.images&&p.images[0])||p.image||'')}" alt=""><div><b>${esc2(p.name)}</b><small>${Number(p.price||0).toLocaleString('ar-EG')} ج.م • ${p.status==='sold'?'مباعة':'متاحة'}</small></div><div class="staff-ad-actions">${canEdit?`<button class="btn" data-edit="${esc2(p.id)}">تعديل</button><button class="btn" data-sold="${esc2(p.id)}">${p.status==='sold'?'إتاحة':'مباعة'}</button>`:''}${canDelete?`<button class="btn danger" data-del="${esc2(p.id)}">حذف</button>`:''}</div></div>`}).join('')||'<div class="empty">لا توجد إعلانات.</div>';box.querySelectorAll('[data-edit]').forEach(btn=>btn.onclick=()=>editStaffAd(items.find(x=>String(x.id)===btn.dataset.edit)));box.querySelectorAll('[data-sold]').forEach(btn=>btn.onclick=async()=>{if(!perms().edit)return;const p=items.find(x=>String(x.id)===btn.dataset.sold);if(!p)return;const fd=new FormData();Object.entries(p).forEach(([k,v])=>{if(k==='images')fd.set(k,Array.isArray(v)?v.join('\n'):v);else if(!['id','image'].includes(k))fd.set(k,v??'')});fd.set('id',p.id);fd.set('status',p.status==='sold'?'available':'sold');await staffApi('/api/admin/products',{method:'POST',body:fd});await loadStaffAds();load()});box.querySelectorAll('[data-del]').forEach(btn=>btn.onclick=async()=>{if(!perms().delete)return;if(!confirm('حذف الإعلان نهائيًا؟'))return;await staffApi('/api/admin/products/'+encodeURIComponent(btn.dataset.del),{method:'DELETE'});await loadStaffAds();load()})}catch(e){box.innerHTML='<div class="empty">'+esc2(e.message)+'</div>'}}
q('#staffRefresh').onclick=loadStaffAds; q('#staffSubRefresh').onclick=loadStaffSubmissions;
function editStaffAd(p){if(!p||!perms().edit)return;const f=q('#staffProductForm');f.elements.id.value=p.id;['name','price','year','mileage','transmission','fuel','status','description'].forEach(k=>f.elements[k].value=p[k]??'');staffImages=Array.isArray(p.images)?[...p.images]:[p.image].filter(Boolean);f.elements.images.value=staffImages.join('\n');renderStaffPreview();q('#staffSaveBtn').textContent='حفظ التعديلات';q('#staffStatus').textContent='تعديل الإعلان ثم اضغط حفظ التعديلات.';q('#staffPanel').scrollTo({top:0,behavior:'smooth'})}
async function loadStaffSubmissions(){if(!perms().approve)return;const box=q('#staffSubmissionsList');if(!box)return;box.innerHTML='<div class="loading">جاري تحميل إعلانات العملاء...</div>';try{const items=await staffApi('/api/admin/car-submissions');box.innerHTML=items.filter(x=>x.status==='pending').reverse().map(x=>`<div class="staff-ad-row"><img src="${esc2(x.images?.[0]||'')}" alt=""><div><b>${esc2(x.carName)}</b><small>${Number(x.price||0).toLocaleString('ar-EG')} ج.م • ${esc2(x.name)} • ${esc2(x.phone)}</small></div><div class="staff-ad-actions"><button class="btn" data-approve="${esc2(x.id)}">موافقة ونشر</button><button class="btn danger" data-reject="${esc2(x.id)}">رفض</button></div></div>`).join('')||'<div class="empty">لا توجد إعلانات عملاء في انتظار الموافقة.</div>';box.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>reviewStaffSubmission(b.dataset.approve,'approve'));box.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>reviewStaffSubmission(b.dataset.reject,'reject'))}catch(e){box.innerHTML='<div class="empty">'+esc2(e.message)+'</div>'}}
async function reviewStaffSubmission(id,action){try{await staffApi('/api/admin/car-submissions/'+encodeURIComponent(id),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});await loadStaffSubmissions();load()}catch(e){alert(e.message)}}
q('#staffModal').addEventListener('click',e=>{if(e.target===modal)closeStaff()});
})();
