const WA='201119295523';let products=[];let cart=JSON.parse(localStorage.getItem('elkheshenCart')||'[]');let currentFilter='all';const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const js=v=>String(v??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'");
async function load(){try{const r=await fetch('/api/products',{cache:'no-store'});if(!r.ok)throw new Error(`API ${r.status}`);products=await r.json();render()}catch(e){$('#productsGrid').innerHTML='<div class="empty">تعذر تحميل السيارات حاليًا. حاول تحديث الصفحة.</div>'}}
function imgs(p){return Array.isArray(p.images)&&p.images.length?p.images.filter(Boolean):[p.image].filter(Boolean)}
function category(p){const s=(p.category||p.type||p.name||'').toLowerCase();if(/suv|jeep|تويوتا راش|سبورتاج|توسان|كريتا|كابتيفا/.test(s))return'suv';if(/sedan|سيدان|e200|c200|النترا|صني|لوجان|bmw 3|a6/.test(s))return'sedan';return'other'}
function render(){const list=currentFilter==='all'?products:products.filter(p=>category(p)===currentFilter);$('#productsGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">لا توجد سيارات في هذا التصنيف حاليًا.</div>'}
function card(p){const pic=imgs(p)[0]||'';const sold=p.status==='sold';return `<article class="car-card ${sold?'sold':''}"><div class="car-image">${pic?`<img src="${esc(pic)}" alt="${esc(p.name)}" onerror="this.style.display='none'">`:''}${sold?'<div class="sold-overlay"><span>مبــــاع</span></div>':''}<button class="heart" onclick="openProduct('${js(p.id)}')" aria-label="التفاصيل">↗</button>${p.badge?`<span class="car-badge">${esc(p.badge)}</span>`:''}</div><div class="car-body"><div class="car-title"><h3>${esc(p.name)}</h3><span class="year">${esc(p.year||'—')}</span></div><div class="specs"><span class="spec">⚙ ${esc(p.transmission||'أوتوماتيك')}</span><span class="spec">⛽ ${esc(p.fuel||'بنزين')}</span><span class="spec">📍 الإسكندرية</span></div><div class="car-price">${Number(p.price||0).toLocaleString('ar-EG')} ج.م</div><div class="car-actions"><button class="btn ${sold?'sold-btn':'btn-primary'}" ${sold?'disabled':''} onclick="${sold?'return false':`add('${js(p.id)}')`}">${sold?'السيارة مباعة':'أضف للسلة 🛒'}</button><button class="icon-action" onclick="openProduct('${js(p.id)}')" aria-label="عرض التفاصيل">↗</button></div></div></article>`}
function add(id){const p=products.find(x=>x.id===id);if(!p||p.status==='sold')return;const i=cart.find(x=>x.id===id);if(i)i.qty++;else cart.push({id,qty:1});save();openCart()}
function save(){localStorage.setItem('elkheshenCart',JSON.stringify(cart));updateCount()}function updateCount(){$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0)}
function openCart(){$('#cartModal').classList.remove('hidden');renderCart()}function renderCart(){const box=$('#cartItems');if(!cart.length){box.innerHTML='<div class="empty">السلة فارغة. اختار سيارة وأضفها للسلة.</div>';$('#cartTotal').textContent='0';return}box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return'';const pic=imgs(p)[0]||'';return `<div class="cart-row"><img class="cart-thumb" src="${esc(pic)}" alt=""><div class="cart-product-info"><b>${esc(p.name)}</b><br><small>${Number(p.price||0).toLocaleString('ar-EG')} ج.م</small></div><div class="qty"><button onclick="changeQty('${js(i.id)}',-1)">−</button>${i.qty}<button onclick="changeQty('${js(i.id)}',1)">+</button></div></div>`}).join('');$('#cartTotal').textContent=cart.reduce((n,i)=>n+i.qty,0)}
function changeQty(id,d){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);save();renderCart()}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const list=imgs(p);const sold=p.status==='sold';const m=$('#productModal');m.innerHTML=`<div class="modal-card product-detail"><button class="close" onclick="closeProduct()">×</button><div class="detail-main"><img id="detailMainImg" src="${esc(list[0]||'')}" alt="${esc(p.name)}"></div><div class="detail-thumbs">${list.map((im,i)=>`<button class="detail-thumb ${i===0?'active':''}" onclick="showDetailImage(${i})"><img src="${esc(im)}" alt=""></button>`).join('')}</div>${p.badge?`<span class="car-badge">${esc(p.badge)}</span>`:''}<h2>${esc(p.name)}</h2><p class="detail-desc">${esc(p.description||'تفاصيل السيارة والتجهيزات والمعلومات تظهر هنا.')}</p><div class="detail-info"><b>بيانات السيارة</b><p>للاستفسار عن الحالة والتفاصيل والمواعيد تواصل معنا مباشرة.</p></div><div class="car-price">${Number(p.price||0).toLocaleString('ar-EG')} ج.م</div>${sold?'<button class="btn sold-btn full" disabled>السيارة مباعة</button>':`<button class="btn btn-primary full" onclick="add('${js(p.id)}');closeProduct()">أضف للسلة 🛒</button>`}</div>`;m.dataset.images=JSON.stringify(list);m.classList.remove('hidden')}
function showDetailImage(i){const m=$('#productModal'),list=JSON.parse(m.dataset.images||'[]');if(list[i])$('#detailMainImg').src=list[i];document.querySelectorAll('.detail-thumb').forEach((b,n)=>b.classList.toggle('active',n===i))}function closeProduct(){$('#productModal').classList.add('hidden')}
$('#cartBtn').onclick=openCart;$('#checkoutBtn').onclick=()=>{if(!cart.length)return alert('السلة فارغة');$('#cartModal').classList.add('hidden');$('#orderModal').classList.remove('hidden')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));$('#orderForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const lines=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `• ${p?.name||i.id} × ${i.qty}`}).join('\n');const msg=`مرحبًا، أريد الاستفسار عن السيارات التالية من Automobile Elkheshen.\n\n${lines}\n\nالاسم: ${f.get('customer')}\nالهاتف: ${f.get('phone')}\nالعنوان: ${f.get('address')}\nملاحظات: ${f.get('note')||'لا يوجد'}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank');cart=[];save();e.target.reset();$('#orderModal').classList.add('hidden')};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});$('#mobileMenu').onclick=()=>$('#mainNav').classList.toggle('open');document.querySelectorAll('#mainNav a').forEach(a=>a.onclick=()=>$('#mainNav').classList.remove('open'));updateCount();load();
