const express=require('express');const multer=require('multer');const crypto=require('crypto');
const app=express();const upload=multer({storage:multer.memoryStorage()});
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'';
const TOKEN_SECRET=process.env.ADMIN_TOKEN_SECRET||ADMIN_PASSWORD||'automobile-elkheshen-change-this-secret';
function b64json(obj){return Buffer.from(JSON.stringify(obj),'utf8').toString('base64url')}
function signToken(payload){const head=b64json({alg:'HS256',typ:'JWT'});const body=b64json({...payload,exp:Date.now()+1000*60*60*12});const sig=crypto.createHmac('sha256',TOKEN_SECRET).update(head+'.'+body).digest('base64url');return head+'.'+body+'.'+sig}
function verifyToken(token){try{const [h,b,sig]=String(token||'').split('.');if(!h||!b||!sig)return null;const expected=crypto.createHmac('sha256',TOKEN_SECRET).update(h+'.'+b).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const payload=JSON.parse(Buffer.from(b,'base64url').toString('utf8'));if(!payload.exp||payload.exp<Date.now())return null;return payload}catch{return null}}
function auth(req,res,next){
  if(ADMIN_PASSWORD){const encoded=String(req.headers['x-admin-password-b64']||'');let supplied='';try{supplied=Buffer.from(encoded,'base64').toString('utf8')}catch{}if(supplied===ADMIN_PASSWORD){req.auth={role:'super'};return next()}}
  const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const payload=verifyToken(token);if(payload&&payload.role==='staff'){req.auth=payload;return next()}
  return res.status(401).json({error:'غير مصرح بالدخول.'});
}
function normalizePermissions(a){const p=a?.permissions||{};const all=a?.role==='admin'||p.all===true;return{publish:all||p.publish!==false,edit:all||!!p.edit,delete:all||!!p.delete,approve:all||!!p.approve}}
function hasPermission(req,perm){return req.auth?.role==='super'||!!req.auth?.permissions?.[perm]}
function requirePermission(perm){return (req,res,next)=>{if(hasPermission(req,perm))return next();return res.status(403).json({error:'هذا الحساب لا يملك الصلاحية المطلوبة.'})}}
function requireAnyPermission(...perms){return (req,res,next)=>{if(perms.some(p=>hasPermission(req,p)))return next();return res.status(403).json({error:'هذا الحساب لا يملك الصلاحية المطلوبة.'})}}
function requireProductWrite(req,res,next){const id=String(req.body?.id||'').trim();return id?requirePermission('edit')(req,res,next):requirePermission('publish')(req,res,next)}
function superAuth(req,res,next){if(ADMIN_PASSWORD){const encoded=String(req.headers['x-admin-password-b64']||'');let supplied='';try{supplied=Buffer.from(encoded,'base64').toString('utf8')}catch{}if(supplied===ADMIN_PASSWORD){req.auth={role:'super'};return next()}}return res.status(401).json({error:'هذه العملية متاحة للأدمن الرئيسي فقط.'})}
function hashPassword(password){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.pbkdf2Sync(String(password),salt,120000,64,'sha512').toString('hex');return {salt,hash,iterations:120000}}
function verifyPassword(password,item){try{return crypto.pbkdf2Sync(String(password),item.salt,item.iterations||120000,64,'sha512').toString('hex')===item.hash}catch{return false}}
const GH_API='https://api.github.com';
function githubConfig(){return{token:process.env.GITHUB_TOKEN,repo:process.env.GITHUB_REPO,branch:process.env.GITHUB_BRANCH||'main',path:process.env.GITHUB_PRODUCTS_PATH||'data/products.json',submissionsPath:process.env.GITHUB_SUBMISSIONS_PATH||'data/car-submissions.json',adminsPath:process.env.GITHUB_ADMINS_PATH||'data/admins.json'}}
async function githubRequest(url,options={}){const cfg=githubConfig();if(!cfg.token||!cfg.repo)throw new Error('اضبط GITHUB_TOKEN و GITHUB_REPO في Vercel أولًا.');const headers={'Accept':'application/vnd.github+json','Authorization':`Bearer ${cfg.token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(options.headers||{})};const response=await fetch(url,{...options,headers});const text=await response.text();let data=null;try{data=JSON.parse(text)}catch{}if(!response.ok)throw new Error(data?.message||`GitHub API error ${response.status}`);return data}
async function readProducts(){const cfg=githubConfig();if(!cfg.token||!cfg.repo)throw new Error('إعدادات قاعدة السيارات غير مكتملة.');const data=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.path}?ref=${encodeURIComponent(cfg.branch)}`);const products=JSON.parse(Buffer.from(String(data.content).replace(/\n/g,''),'base64').toString('utf8'));if(!Array.isArray(products))throw new Error('ملف المنتجات غير صالح.');return products.map(normalizeProduct)}
async function writeProducts(products,message){const cfg=githubConfig();if(!cfg.token||!cfg.repo)throw new Error('اضبط GITHUB_TOKEN و GITHUB_REPO في Vercel أولًا.');let sha=null;try{const current=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.path}?ref=${encodeURIComponent(cfg.branch)}`);sha=current.sha}catch{}const content=Buffer.from(JSON.stringify(products,null,2),'utf8').toString('base64');const body={message:message||'Update products',content,branch:cfg.branch};if(sha)body.sha=sha;return githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.path}`,{method:'PUT',body:JSON.stringify(body)})}
function githubRawUrl(path){const cfg=githubConfig();return `https://raw.githubusercontent.com/${cfg.repo}/${encodeURIComponent(cfg.branch)}/${path.split('/').map(encodeURIComponent).join('/')}`}
async function uploadFileToGithub(file){const cfg=githubConfig();if(!cfg.token||!cfg.repo)throw new Error('اضبط GITHUB_TOKEN و GITHUB_REPO في Vercel أولًا.');const ext=(file.originalname.match(/\.[a-zA-Z0-9]+$/)||[''])[0].toLowerCase();const safeExt=['.jpg','.jpeg','.png','.webp','.gif'].includes(ext)?ext:'.jpg';const base=String(file.originalname||'image').replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,50)||'image';const filename=`${Date.now()}-${Math.random().toString(36).slice(2,8)}-${base}${safeExt}`;const path=`uploads/${filename}`;await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Upload product image ${filename}`,content:file.buffer.toString('base64'),branch:cfg.branch})});return githubRawUrl(path)}
function normalizeProduct(p){const images=Array.isArray(p.images)&&p.images.length?p.images.filter(Boolean).map(String):[p.image].filter(Boolean);return{...p,id:String(p.id||`product-${Date.now()}`),image:String(p.image||images[0]||''),images,mileage:Number(p.mileage||0),status:['sold','available'].includes(p.status)?p.status:'available'}}
function cleanProduct(body,old={}){const name=String(body.name??old.name??'').trim();const price=Number(body.price??old.price??0);let rawImages=body.images,images=[];if(Array.isArray(rawImages))images=rawImages;else if(typeof rawImages==='string')images=rawImages.split(/\r?\n|,/);images=images.map(x=>String(x||'').trim()).filter(Boolean);const single=String(body.image??old.image??'').trim();if(!images.length&&single)images=[single];if(!images.length&&Array.isArray(old.images))images=old.images.filter(Boolean);if(!images.length)throw new Error('أضف صورة واحدة على الأقل.');if(!name)throw new Error('اسم السيارة مطلوب.');if(!Number.isFinite(price)||price<0)throw new Error('السعر غير صحيح.');const status=String(body.status??old.status??'available');const mileage=Number(body.mileage??old.mileage??0);if(!Number.isFinite(mileage)||mileage<0)throw new Error('عداد الكيلومترات غير صحيح.');return{id:String(body.id??old.id??'').trim()||`product-${Date.now()}`,name,price,year:String(body.year??old.year??'').trim(),category:String(body.category??old.category??'').trim(),transmission:String(body.transmission??old.transmission??'').trim(),fuel:String(body.fuel??old.fuel??'').trim(),mileage,description:String(body.description??old.description??'').trim(),image:images[0],images,status:status==='sold'?'sold':'available',...(String(body.badge??old.badge??'').trim()?{badge:String(body.badge??old.badge).trim()}:{})}}

async function readSubmissions(){const cfg=githubConfig();try{const data=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.submissionsPath}?ref=${encodeURIComponent(cfg.branch)}`);const value=JSON.parse(Buffer.from(String(data.content).replace(/\n/g,''),'base64').toString('utf8'));return Array.isArray(value)?value:[]}catch(e){if(String(e.message||'').includes('404'))return [];throw e}}
async function writeSubmissions(items,message){const cfg=githubConfig();let sha=null;try{const current=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.submissionsPath}?ref=${encodeURIComponent(cfg.branch)}`);sha=current.sha}catch{}const content=Buffer.from(JSON.stringify(items,null,2),'utf8').toString('base64');const body={message:message||'Update car submissions',content,branch:cfg.branch};if(sha)body.sha=sha;return githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.submissionsPath}`,{method:'PUT',body:JSON.stringify(body)})}
async function readAdmins(){const cfg=githubConfig();try{const data=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.adminsPath}?ref=${encodeURIComponent(cfg.branch)}`);const value=JSON.parse(Buffer.from(String(data.content).replace(/\n/g,''),'base64').toString('utf8'));return Array.isArray(value)?value:[]}catch(e){if(String(e.message||'').includes('404'))return [];throw e}}
async function writeAdmins(items,message){const cfg=githubConfig();let sha=null;try{const current=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.adminsPath}?ref=${encodeURIComponent(cfg.branch)}`);sha=current.sha}catch{}const content=Buffer.from(JSON.stringify(items,null,2),'utf8').toString('base64');const body={message:message||'Update staff accounts',content,branch:cfg.branch};if(sha)body.sha=sha;return githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.adminsPath}`,{method:'PUT',body:JSON.stringify(body)})}
function cleanSubmission(body,images){const name=String(body.name||'').trim(),phone=String(body.phone||'').trim(),carName=String(body.carName||'').trim();const price=Number(body.price||0),mileage=Number(body.mileage||0);if(!name||!phone||!carName)throw new Error('الاسم ورقم الهاتف واسم السيارة مطلوبون.');if(!Number.isFinite(price)||price<0)throw new Error('السعر غير صحيح.');if(!Number.isFinite(mileage)||mileage<0)throw new Error('عداد الكيلومترات غير صحيح.');if(!images.length)throw new Error('أضف صورة واحدة على الأقل للسيارة.');return{id:`submission-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name,phone,carName,price,mileage,year:String(body.year||'').trim(),transmission:String(body.transmission||'').trim(),fuel:String(body.fuel||'').trim(),description:String(body.description||'').trim(),images,status:'pending',createdAt:new Date().toISOString()}}

function handleError(res,err){console.error(err);return res.status(500).json({error:err?.message||'حدث خطأ أثناء حفظ السيارات.'})}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'automobile-elkheshen-api',time:new Date().toISOString()}));
app.post('/api/staff/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase();const password=String(req.body.password||'');if(!email||!password)return res.status(400).json({error:'اكتب البريد الإلكتروني وكلمة المرور.'});const admins=await readAdmins();const a=admins.find(x=>String(x.email||'').toLowerCase()===email&&x.active!==false);if(!a||!verifyPassword(password,a))return res.status(401).json({error:'البريد الإلكتروني أو كلمة المرور غير صحيحة.'});const permissions=normalizePermissions(a);res.json({ok:true,token:signToken({role:'staff',id:a.id,email:a.email,name:a.name||a.email,permissions}),user:{id:a.id,email:a.email,name:a.name||a.email,permissions}})}catch(e){handleError(res,e)}});
app.get('/api/staff/me',auth,async(req,res)=>{try{if(req.auth.role==='super')return res.json({ok:true,user:req.auth});const admins=await readAdmins();const a=admins.find(x=>x.id===req.auth.id&&x.active!==false);if(!a)return res.status(401).json({error:'الحساب غير نشط أو تم حذفه.'});const permissions=normalizePermissions(a);res.json({ok:true,user:{id:a.id,email:a.email,name:a.name||a.email,permissions}})}catch(e){handleError(res,e)}});
app.get('/api/admin/staff',superAuth,async(req,res)=>{try{const admins=await readAdmins();res.json(admins.map(x=>({id:x.id,name:x.name,email:x.email,active:x.active!==false,permissions:{publish:x.permissions?.publish!==false,edit:!!x.permissions?.edit,delete:!!x.permissions?.delete,approve:!!x.permissions?.approve},createdAt:x.createdAt})));}catch(e){handleError(res,e)}});
app.post('/api/admin/staff',superAuth,async(req,res)=>{try{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!name||!email||password.length<6)return res.status(400).json({error:'الاسم والبريد وكلمة مرور 6 أحرف على الأقل مطلوبة.'});const admins=await readAdmins();if(admins.some(x=>String(x.email||'').toLowerCase()===email))return res.status(409).json({error:'هذا البريد مستخدم بالفعل.'});const permissions={publish:req.body.publish!=='false',edit:req.body.edit==='true',delete:req.body.delete==='true',approve:req.body.approve==='true'};admins.push({id:`staff-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name,email,...hashPassword(password),permissions,active:true,createdAt:new Date().toISOString()});await writeAdmins(admins,`Add staff ${email}`);res.json({ok:true});}catch(e){handleError(res,e)}});
app.put('/api/admin/staff/:id',superAuth,async(req,res)=>{try{const admins=await readAdmins(),i=admins.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'حساب الأدمن غير موجود.'});if(typeof req.body.active!=='undefined')admins[i].active=!!req.body.active;if(req.body.permissions&&typeof req.body.permissions==='object')admins[i].permissions={publish:req.body.permissions.publish!==false,edit:!!req.body.permissions.edit,delete:!!req.body.permissions.delete,approve:!!req.body.permissions.approve};const password=String(req.body.password||'');if(password){if(password.length<6)return res.status(400).json({error:'كلمة المرور يجب أن تكون 6 أحرف على الأقل.'});Object.assign(admins[i],hashPassword(password));}await writeAdmins(admins,`Update staff ${req.params.id}`);res.json({ok:true});}catch(e){handleError(res,e)}});
app.delete('/api/admin/staff/:id',superAuth,async(req,res)=>{try{const admins=await readAdmins(),next=admins.filter(x=>x.id!==req.params.id);if(next.length===admins.length)return res.status(404).json({error:'حساب الأدمن غير موجود.'});await writeAdmins(next,`Delete staff ${req.params.id}`);res.json({ok:true});}catch(e){handleError(res,e)}});

app.get('/api/products',async(req,res)=>{try{res.json(await readProducts())}catch(e){handleError(res,e)}});
app.get('/api/admin/products',auth,async(req,res)=>{try{res.json(await readProducts())}catch(e){handleError(res,e)}});
app.post('/api/admin/upload-images',auth,requireAnyPermission('publish','edit'),upload.array('images',12),async(req,res)=>{try{const files=req.files||[];if(!files.length)return res.status(400).json({error:'اختر صورة واحدة على الأقل.'});const allowed=['image/jpeg','image/png','image/webp','image/gif'];for(const f of files){if(!allowed.includes(f.mimetype))return res.status(400).json({error:'مسموح فقط JPG وPNG وWEBP وGIF.'});if(f.size>2*1024*1024)return res.status(400).json({error:'حجم كل صورة يجب ألا يتجاوز 2 ميجابايت.'})}if(files.reduce((n,f)=>n+f.size,0)>4*1024*1024)return res.status(400).json({error:'إجمالي الصور في الرفع الواحد يجب ألا يتجاوز 4 ميجابايت.'});const urls=[];for(const f of files)urls.push(await uploadFileToGithub(f));res.json({ok:true,urls})}catch(e){handleError(res,e)}});
app.post('/api/admin/products',auth,upload.none(),requireProductWrite,async(req,res)=>{try{const products=await readProducts();const product=cleanProduct(req.body);const i=products.findIndex(p=>p.id===product.id);if(i>=0)products[i]=product;else products.push(product);await writeProducts(products,i>=0?`Update product ${product.id}`:`Add product ${product.id}`);res.json({ok:true,product})}catch(e){handleError(res,e)}});
app.put('/api/admin/products/:id',auth,requirePermission('edit'),upload.none(),async(req,res)=>{try{const products=await readProducts();const i=products.findIndex(p=>p.id===req.params.id);if(i<0)return res.status(404).json({error:'السيارة غير موجودة.'});const product=cleanProduct({...req.body,id:req.params.id},products[i]);products[i]=product;await writeProducts(products,`Update product ${product.id}`);res.json({ok:true,product})}catch(e){handleError(res,e)}});
app.delete('/api/admin/products/:id',auth,requirePermission('delete'),async(req,res)=>{try{const products=await readProducts();const next=products.filter(p=>p.id!==req.params.id);if(next.length===products.length)return res.status(404).json({error:'السيارة غير موجودة.'});await writeProducts(next,`Delete product ${req.params.id}`);res.json({ok:true})}catch(e){handleError(res,e)}});

app.get('/api/car-submissions',async(req,res)=>{try{const items=await readSubmissions();res.json(items.filter(x=>x.status==='approved'))}catch(e){handleError(res,e)}});
app.post('/api/car-submissions',upload.array('images',8),async(req,res)=>{try{const files=req.files||[];const allowed=['image/jpeg','image/png','image/webp','image/gif'];for(const f of files){if(!allowed.includes(f.mimetype))return res.status(400).json({error:'مسموح فقط JPG وPNG وWEBP وGIF.'});if(f.size>2*1024*1024)return res.status(400).json({error:'حجم كل صورة يجب ألا يتجاوز 2 ميجابايت.'})}if(files.length>8)return res.status(400).json({error:'8 صور كحد أقصى.'});if(files.reduce((n,f)=>n+f.size,0)>6*1024*1024)return res.status(400).json({error:'إجمالي الصور يجب ألا يتجاوز 6 ميجابايت.'});const urls=[];for(const f of files)urls.push(await uploadFileToGithub(f));const item=cleanSubmission(req.body,urls);const items=await readSubmissions();items.push(item);await writeSubmissions(items,`New car submission ${item.id}`);res.json({ok:true,message:'تم إرسال السيارة للمراجعة.'})}catch(e){handleError(res,e)}});
app.get('/api/admin/car-submissions',auth,requirePermission('approve'),async(req,res)=>{try{res.json(await readSubmissions())}catch(e){handleError(res,e)}});
app.put('/api/admin/car-submissions/:id',auth,requirePermission('approve'),async(req,res)=>{try{const items=await readSubmissions(),i=items.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'الإعلان غير موجود.'});const action=String(req.body.action||'').trim();if(action==='reject'){items[i].status='rejected';await writeSubmissions(items,`Reject car submission ${req.params.id}`);return res.json({ok:true})}if(action==='approve'){const s=items[i];const products=await readProducts();const product=cleanProduct({id:`customer-${Date.now()}`,name:s.carName,price:s.price,year:s.year,transmission:s.transmission,fuel:s.fuel,mileage:s.mileage,description:s.description,images:s.images,status:'available'},{});products.push(product);await writeProducts(products,`Approve customer car ${s.id}`);items[i].status='approved';items[i].approvedProductId=product.id;await writeSubmissions(items,`Approve car submission ${s.id}`);return res.json({ok:true,product})}return res.status(400).json({error:'إجراء غير صحيح.'})}catch(e){handleError(res,e)}});
app.delete('/api/admin/car-submissions/:id',auth,requirePermission('delete'),async(req,res)=>{try{const items=await readSubmissions(),next=items.filter(x=>x.id!==req.params.id);if(next.length===items.length)return res.status(404).json({error:'الإعلان غير موجود.'});await writeSubmissions(next,`Delete car submission ${req.params.id}`);res.json({ok:true})}catch(e){handleError(res,e)}});
app.post('/api/order',async(req,res)=>res.json({ok:true,orderId:`AE-${Date.now().toString().slice(-8)}`}));
module.exports=app;
