const express=require('express');
const multer=require('multer');
const fs=require('fs');const path=require('path');const crypto=require('crypto');
const app=express();
app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true,limit:'2mb'}));
const ROOT=path.join(__dirname,'..');const DATA=path.join(ROOT,'data');const PRODUCTS=path.join(DATA,'products.json');const ADMINS=path.join(DATA,'admins.json');
fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(path.join(ROOT,'uploads'),{recursive:true});
if(!fs.existsSync(PRODUCTS))fs.writeFileSync(PRODUCTS,'[]');
if(!fs.existsSync(ADMINS))fs.writeFileSync(ADMINS,'[]');
const upload=multer({storage:multer.memoryStorage(),limits:{files:12,fileSize:2*1024*1024}});
const envPass=process.env.ADMIN_PASSWORD||'change-this-password';
const envEmail=(process.env.ADMIN_EMAIL||'admin@automobile-elkheshen.local').toLowerCase();
function readJson(f,def=[]){try{const x=JSON.parse(fs.readFileSync(f,'utf8'));return Array.isArray(x)?x:def}catch{return def}}
function writeJson(f,x){fs.writeFileSync(f,JSON.stringify(x,null,2),'utf8')}
function hash(p,salt=crypto.randomBytes(16).toString('hex')){return {salt,hash:crypto.pbkdf2Sync(p,salt,120000,32,'sha256').toString('hex')}}
function verify(p,a){if(!a?.salt||!a?.hash)return false;return crypto.timingSafeEqual(Buffer.from(hash(p,a.salt).hash,'hex'),Buffer.from(a.hash,'hex'))}
function sign(payload){const body=Buffer.from(JSON.stringify(payload)).toString('base64url');const sig=crypto.createHmac('sha256',process.env.ADMIN_TOKEN_SECRET||envPass).update(body).digest('base64url');return body+'.'+sig}
function verifyToken(t){try{const [b,s]=String(t||'').split('.');const exp=crypto.createHmac('sha256',process.env.ADMIN_TOKEN_SECRET||envPass).update(b).digest('base64url');if(!b||!s||s!==exp)return null;const p=JSON.parse(Buffer.from(b,'base64url'));if(p.exp<Date.now())return null;return p}catch{return null}}
function token(req){return req.headers.authorization?.replace(/^Bearer\s+/i,'')||req.headers['x-admin-token']}
function auth(req,res,next){const p=verifyToken(token(req));if(p?.role==='admin'||p?.role==='super'){req.admin=p;return next()}return res.status(401).json({error:'يجب تسجيل الدخول كأدمن.'})}
function superAuth(req,res,next){auth(req,res,()=>req.admin.role==='super'?next():res.status(403).json({error:'هذا الإجراء للأدمن الرئيسي فقط.'}))}
function products(){return readJson(PRODUCTS,[])}
function publicProducts(res){res.json(products().filter(x=>x.active!==false))}
app.get('/api/health',(_q,res)=>res.json({ok:true}));
app.get('/api/products',(_q,res)=>publicProducts(res));app.get('/products',(_q,res)=>publicProducts(res));
app.post('/api/admin/login',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(email===envEmail&&password===envPass)return res.json({role:'super',email,token:sign({email,role:'super',exp:Date.now()+1000*60*60*12})});const a=readJson(ADMINS,[]).find(x=>x.email===email&&x.active!==false);if(a&&verify(password,a))return res.json({role:'admin',email,name:a.name,token:sign({email,role:'admin',adminId:a.id,exp:Date.now()+1000*60*60*12})});return res.status(401).json({error:'البريد الإلكتروني أو كلمة المرور غير صحيحة.'})});
app.get('/api/admin/admins',superAuth,(_q,res)=>res.json(readJson(ADMINS,[]).map(x=>({id:x.id,name:x.name,email:x.email,active:x.active!==false}))));
app.post('/api/admin/admins',superAuth,(req,res)=>{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!name||!email||password.length<6)return res.status(400).json({error:'اكتب الاسم والبريد وكلمة مرور 6 أحرف على الأقل.'});const a=readJson(ADMINS,[]);if(email===envEmail||a.some(x=>x.email===email))return res.status(409).json({error:'هذا البريد مستخدم بالفعل.'});const h=hash(password);const item={id:Date.now().toString(),name,email,active:true,...h};a.push(item);writeJson(ADMINS,a);res.json({id:item.id,name,email,active:true})});
app.put('/api/admin/admins/:id',superAuth,(req,res)=>{const a=readJson(ADMINS,[]),i=a.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'الأدمن غير موجود.'});if(typeof req.body.active==='boolean')a[i].active=req.body.active;if(req.body.password){if(String(req.body.password).length<6)return res.status(400).json({error:'كلمة المرور يجب أن تكون 6 أحرف على الأقل.'});Object.assign(a[i],hash(String(req.body.password)))}writeJson(ADMINS,a);res.json({ok:true})});
app.delete('/api/admin/admins/:id',superAuth,(req,res)=>{const a=readJson(ADMINS,[]).filter(x=>x.id!==req.params.id);writeJson(ADMINS,a);res.json({ok:true})});
function normalize(body,images,existing={}){return {id:String(body.id||existing.id||Date.now()),name:String(body.name||existing.name||'').trim(),price:Number(body.price||existing.price||0),year:String(body.year||existing.year||''),mileage:Number(body.mileage||existing.mileage||0),category:String(body.category||existing.category||'other'),transmission:String(body.transmission||existing.transmission||'أوتوماتيك'),fuel:String(body.fuel||existing.fuel||'بنزين'),badge:String(body.badge||existing.badge||''),description:String(body.description||existing.description||''),images:images?.length?images:(existing.images||[existing.image].filter(Boolean)),image:(images?.[0]||existing.image||''),status:String(body.status||existing.status||'available'),active:body.active==='false'?false:true,postedBy:existing.postedBy||null,updatedAt:new Date().toISOString()}}
app.get('/api/admin/products',auth,(_q,res)=>res.json(products()));
app.post('/api/admin/upload-images',auth,upload.array('images',12),(req,res)=>{const urls=(req.files||[]).map(f=>`data:${f.mimetype};base64,${f.buffer.toString('base64')}`);res.json({urls})});
app.post('/api/admin/products',auth,upload.array('images',12),(req,res)=>{const list=products(),id=String(req.body.id||Date.now()),old=list.find(x=>String(x.id)===id)||{};let images=String(req.body.images||'').split(/\r?\n+/).map(x=>x.trim()).filter(Boolean);if(req.files?.length)images=(req.files||[]).map(f=>`data:${f.mimetype};base64,${f.buffer.toString('base64')}`);const p=normalize(req.body,images,old);if(!p.name||!p.price)return res.status(400).json({error:'اكتب اسم السيارة والسعر.'});p.postedBy={email:req.admin.email,role:req.admin.role};const i=list.findIndex(x=>String(x.id)===id);if(i>=0)list[i]=p;else list.push(p);writeJson(PRODUCTS,list);res.json(p)});
app.put('/api/admin/products/:id',auth,(req,res)=>{const list=products(),i=list.findIndex(x=>String(x.id)===req.params.id);if(i<0)return res.status(404).json({error:'السيارة غير موجودة.'});list[i]=normalize(req.body,[],list[i]);list[i].postedBy={email:req.admin.email,role:req.admin.role};writeJson(PRODUCTS,list);res.json(list[i])});
app.delete('/api/admin/products/:id',auth,(req,res)=>{writeJson(PRODUCTS,products().filter(x=>String(x.id)!==req.params.id));res.json({ok:true})});
app.get('/api/admin/car-submissions',auth,(_q,res)=>res.json(readJson(path.join(DATA,'car-submissions.json'),[])));
app.post('/api/car-submissions',upload.array('images',8),(req,res)=>{const f=req.files||[];const file=path.join(DATA,'car-submissions.json');const a=readJson(file,[]);const images=f.map(x=>`data:${x.mimetype};base64,${x.buffer.toString('base64')}`);a.push({...req.body,id:Date.now().toString(),status:'pending',images,createdAt:new Date().toISOString()});writeJson(file,a);res.json({ok:true})});
app.put('/api/admin/car-submissions/:id',auth,(req,res)=>{const file=path.join(DATA,'car-submissions.json'),a=readJson(file,[]),i=a.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'الطلب غير موجود.'});const x=a[i],action=req.body.action;if(action==='approve'){const list=products();const p=normalize({name:x.carName,price:x.price,year:x.year,mileage:x.mileage,transmission:x.transmission,fuel:x.fuel,description:x.description,category:'other'},x.images,{id:'sub-'+x.id});list.push(p);writeJson(PRODUCTS,list);x.status='approved'}else if(action==='reject')x.status='rejected';else return res.status(400).json({error:'إجراء غير صحيح.'});writeJson(file,a);res.json(x)});
app.delete('/api/admin/car-submissions/:id',auth,(req,res)=>{const file=path.join(DATA,'car-submissions.json');writeJson(file,readJson(file,[]).filter(x=>x.id!==req.params.id));res.json({ok:true})});
app.use(express.static(ROOT));module.exports=app;
