const express=require('express');const multer=require('multer');
const app=express();const upload=multer({storage:multer.memoryStorage()});
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'';
function auth(req,res,next){if(!ADMIN_PASSWORD)return res.status(500).json({error:'لم يتم ضبط ADMIN_PASSWORD على Vercel.'});const encoded=String(req.headers['x-admin-password-b64']||'');let supplied='';try{supplied=Buffer.from(encoded,'base64').toString('utf8')}catch{}if(supplied!==ADMIN_PASSWORD)return res.status(401).json({error:'كلمة المرور غير صحيحة.'});next()}
const GH_API='https://api.github.com';
function githubConfig(){return{token:process.env.GITHUB_TOKEN,repo:process.env.GITHUB_REPO,branch:process.env.GITHUB_BRANCH||'main',path:process.env.GITHUB_PRODUCTS_PATH||'data/products.json',submissionsPath:process.env.GITHUB_SUBMISSIONS_PATH||'data/car-submissions.json'}}
async function githubRequest(url,options={}){const cfg=githubConfig();if(!cfg.token||!cfg.repo)throw new Error('اضبط GITHUB_TOKEN و GITHUB_REPO في Vercel أولًا.');const headers={'Accept':'application/vnd.github+json','Authorization':`Bearer ${cfg.token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(options.headers||{})};const response=await fetch(url,{...options,headers});const text=await response.text();let data=null;try{data=JSON.parse(text)}catch{}if(!response.ok)throw new Error(data?.message||`GitHub API error ${response.status}`);return data}
async function readProducts(){const cfg=githubConfig();if(!cfg.token||!cfg.repo)throw new Error('إعدادات قاعدة السيارات غير مكتملة.');const data=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.path}?ref=${encodeURIComponent(cfg.branch)}`);const products=JSON.parse(Buffer.from(String(data.content).replace(/\n/g,''),'base64').toString('utf8'));if(!Array.isArray(products))throw new Error('ملف المنتجات غير صالح.');return products.map(normalizeProduct)}
async function writeProducts(products,message){const cfg=githubConfig();if(!cfg.token||!cfg.repo)throw new Error('اضبط GITHUB_TOKEN و GITHUB_REPO في Vercel أولًا.');let sha=null;try{const current=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.path}?ref=${encodeURIComponent(cfg.branch)}`);sha=current.sha}catch{}const content=Buffer.from(JSON.stringify(products,null,2),'utf8').toString('base64');const body={message:message||'Update products',content,branch:cfg.branch};if(sha)body.sha=sha;return githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.path}`,{method:'PUT',body:JSON.stringify(body)})}
function githubRawUrl(path){const cfg=githubConfig();return `https://raw.githubusercontent.com/${cfg.repo}/${encodeURIComponent(cfg.branch)}/${path.split('/').map(encodeURIComponent).join('/')}`}
async function uploadFileToGithub(file){const cfg=githubConfig();if(!cfg.token||!cfg.repo)throw new Error('اضبط GITHUB_TOKEN و GITHUB_REPO في Vercel أولًا.');const ext=(file.originalname.match(/\.[a-zA-Z0-9]+$/)||[''])[0].toLowerCase();const safeExt=['.jpg','.jpeg','.png','.webp','.gif'].includes(ext)?ext:'.jpg';const base=String(file.originalname||'image').replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,50)||'image';const filename=`${Date.now()}-${Math.random().toString(36).slice(2,8)}-${base}${safeExt}`;const path=`uploads/${filename}`;await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Upload product image ${filename}`,content:file.buffer.toString('base64'),branch:cfg.branch})});return githubRawUrl(path)}
function normalizeProduct(p){const images=Array.isArray(p.images)&&p.images.length?p.images.filter(Boolean).map(String):[p.image].filter(Boolean);return{...p,id:String(p.id||`product-${Date.now()}`),image:String(p.image||images[0]||''),images,mileage:Number(p.mileage||0),status:['sold','available'].includes(p.status)?p.status:'available'}}
function cleanProduct(body,old={}){const name=String(body.name??old.name??'').trim();const price=Number(body.price??old.price??0);let rawImages=body.images,images=[];if(Array.isArray(rawImages))images=rawImages;else if(typeof rawImages==='string')images=rawImages.split(/\r?\n|,/);images=images.map(x=>String(x||'').trim()).filter(Boolean);const single=String(body.image??old.image??'').trim();if(!images.length&&single)images=[single];if(!images.length&&Array.isArray(old.images))images=old.images.filter(Boolean);if(!images.length)throw new Error('أضف صورة واحدة على الأقل.');if(!name)throw new Error('اسم السيارة مطلوب.');if(!Number.isFinite(price)||price<0)throw new Error('السعر غير صحيح.');const status=String(body.status??old.status??'available');const mileage=Number(body.mileage??old.mileage??0);if(!Number.isFinite(mileage)||mileage<0)throw new Error('عداد الكيلومترات غير صحيح.');return{id:String(body.id??old.id??'').trim()||`product-${Date.now()}`,name,price,year:String(body.year??old.year??'').trim(),category:String(body.category??old.category??'').trim(),transmission:String(body.transmission??old.transmission??'').trim(),fuel:String(body.fuel??old.fuel??'').trim(),mileage,description:String(body.description??old.description??'').trim(),image:images[0],images,status:status==='sold'?'sold':'available',...(String(body.badge??old.badge??'').trim()?{badge:String(body.badge??old.badge).trim()}:{})}}

async function readSubmissions(){const cfg=githubConfig();try{const data=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.submissionsPath}?ref=${encodeURIComponent(cfg.branch)}`);const value=JSON.parse(Buffer.from(String(data.content).replace(/\n/g,''),'base64').toString('utf8'));return Array.isArray(value)?value:[]}catch(e){if(String(e.message||'').includes('404'))return [];throw e}}
async function writeSubmissions(items,message){const cfg=githubConfig();let sha=null;try{const current=await githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.submissionsPath}?ref=${encodeURIComponent(cfg.branch)}`);sha=current.sha}catch{}const content=Buffer.from(JSON.stringify(items,null,2),'utf8').toString('base64');const body={message:message||'Update car submissions',content,branch:cfg.branch};if(sha)body.sha=sha;return githubRequest(`${GH_API}/repos/${cfg.repo}/contents/${cfg.submissionsPath}`,{method:'PUT',body:JSON.stringify(body)})}
function cleanSubmission(body,images){const name=String(body.name||'').trim(),phone=String(body.phone||'').trim(),carName=String(body.carName||'').trim();const price=Number(body.price||0),mileage=Number(body.mileage||0);if(!name||!phone||!carName)throw new Error('الاسم ورقم الهاتف واسم السيارة مطلوبون.');if(!Number.isFinite(price)||price<0)throw new Error('السعر غير صحيح.');if(!Number.isFinite(mileage)||mileage<0)throw new Error('عداد الكيلومترات غير صحيح.');if(!images.length)throw new Error('أضف صورة واحدة على الأقل للسيارة.');return{id:`submission-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name,phone,carName,price,mileage,year:String(body.year||'').trim(),transmission:String(body.transmission||'').trim(),fuel:String(body.fuel||'').trim(),description:String(body.description||'').trim(),images,status:'pending',createdAt:new Date().toISOString()}}

function handleError(res,err){console.error(err);return res.status(500).json({error:err?.message||'حدث خطأ أثناء حفظ السيارات.'})}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'automobile-elkheshen-api',time:new Date().toISOString()}));
app.get('/api/products',async(req,res)=>{try{res.json(await readProducts())}catch(e){handleError(res,e)}});
app.get('/api/admin/products',auth,async(req,res)=>{try{res.json(await readProducts())}catch(e){handleError(res,e)}});
app.post('/api/admin/upload-images',auth,upload.array('images',12),async(req,res)=>{try{const files=req.files||[];if(!files.length)return res.status(400).json({error:'اختر صورة واحدة على الأقل.'});const allowed=['image/jpeg','image/png','image/webp','image/gif'];for(const f of files){if(!allowed.includes(f.mimetype))return res.status(400).json({error:'مسموح فقط JPG وPNG وWEBP وGIF.'});if(f.size>2*1024*1024)return res.status(400).json({error:'حجم كل صورة يجب ألا يتجاوز 2 ميجابايت.'})}if(files.reduce((n,f)=>n+f.size,0)>4*1024*1024)return res.status(400).json({error:'إجمالي الصور في الرفع الواحد يجب ألا يتجاوز 4 ميجابايت.'});const urls=[];for(const f of files)urls.push(await uploadFileToGithub(f));res.json({ok:true,urls})}catch(e){handleError(res,e)}});
app.post('/api/admin/products',auth,upload.none(),async(req,res)=>{try{const products=await readProducts();const product=cleanProduct(req.body);const i=products.findIndex(p=>p.id===product.id);if(i>=0)products[i]=product;else products.push(product);await writeProducts(products,i>=0?`Update product ${product.id}`:`Add product ${product.id}`);res.json({ok:true,product})}catch(e){handleError(res,e)}});
app.put('/api/admin/products/:id',auth,upload.none(),async(req,res)=>{try{const products=await readProducts();const i=products.findIndex(p=>p.id===req.params.id);if(i<0)return res.status(404).json({error:'السيارة غير موجودة.'});const product=cleanProduct({...req.body,id:req.params.id},products[i]);products[i]=product;await writeProducts(products,`Update product ${product.id}`);res.json({ok:true,product})}catch(e){handleError(res,e)}});
app.delete('/api/admin/products/:id',auth,async(req,res)=>{try{const products=await readProducts();const next=products.filter(p=>p.id!==req.params.id);if(next.length===products.length)return res.status(404).json({error:'السيارة غير موجودة.'});await writeProducts(next,`Delete product ${req.params.id}`);res.json({ok:true})}catch(e){handleError(res,e)}});

app.get('/api/car-submissions',async(req,res)=>{try{const items=await readSubmissions();res.json(items.filter(x=>x.status==='approved'))}catch(e){handleError(res,e)}});
app.post('/api/car-submissions',upload.array('images',8),async(req,res)=>{try{const files=req.files||[];const allowed=['image/jpeg','image/png','image/webp','image/gif'];for(const f of files){if(!allowed.includes(f.mimetype))return res.status(400).json({error:'مسموح فقط JPG وPNG وWEBP وGIF.'});if(f.size>2*1024*1024)return res.status(400).json({error:'حجم كل صورة يجب ألا يتجاوز 2 ميجابايت.'})}if(files.length>8)return res.status(400).json({error:'8 صور كحد أقصى.'});if(files.reduce((n,f)=>n+f.size,0)>6*1024*1024)return res.status(400).json({error:'إجمالي الصور يجب ألا يتجاوز 6 ميجابايت.'});const urls=[];for(const f of files)urls.push(await uploadFileToGithub(f));const item=cleanSubmission(req.body,urls);const items=await readSubmissions();items.push(item);await writeSubmissions(items,`New car submission ${item.id}`);res.json({ok:true,message:'تم إرسال السيارة للمراجعة.'})}catch(e){handleError(res,e)}});
app.get('/api/admin/car-submissions',auth,async(req,res)=>{try{res.json(await readSubmissions())}catch(e){handleError(res,e)}});
app.put('/api/admin/car-submissions/:id',auth,async(req,res)=>{try{const items=await readSubmissions(),i=items.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'الإعلان غير موجود.'});const action=String(req.body.action||'').trim();if(action==='reject'){items[i].status='rejected';await writeSubmissions(items,`Reject car submission ${req.params.id}`);return res.json({ok:true})}if(action==='approve'){const s=items[i];const products=await readProducts();const product=cleanProduct({id:`customer-${Date.now()}`,name:s.carName,price:s.price,year:s.year,transmission:s.transmission,fuel:s.fuel,mileage:s.mileage,description:s.description,images:s.images,status:'available'},{});products.push(product);await writeProducts(products,`Approve customer car ${s.id}`);items[i].status='approved';items[i].approvedProductId=product.id;await writeSubmissions(items,`Approve car submission ${s.id}`);return res.json({ok:true,product})}return res.status(400).json({error:'إجراء غير صحيح.'})}catch(e){handleError(res,e)}});
app.delete('/api/admin/car-submissions/:id',auth,async(req,res)=>{try{const items=await readSubmissions(),next=items.filter(x=>x.id!==req.params.id);if(next.length===items.length)return res.status(404).json({error:'الإعلان غير موجود.'});await writeSubmissions(next,`Delete car submission ${req.params.id}`);res.json({ok:true})}catch(e){handleError(res,e)}});
app.post('/api/order',async(req,res)=>res.json({ok:true,orderId:`AE-${Date.now().toString().slice(-8)}`}));
module.exports=app;
