const express=require('express');
const multer=require('multer');
const crypto=require('crypto');
const app=express();
const upload=multer({storage:multer.memoryStorage(),limits:{files:12,fileSize:2*1024*1024}});
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:true,limit:'1mb'}));

const GH='https://api.github.com';
const defaults=[];
const cfg=()=>({token:process.env.GITHUB_TOKEN,repo:process.env.GITHUB_REPO,branch:process.env.GITHUB_BRANCH||'main',path:process.env.GITHUB_PRODUCTS_PATH||'data/products.json'});
function password(req){const b=req.get('x-admin-password-b64');if(b){try{return Buffer.from(b,'base64').toString('utf8')}catch{}}return req.get('x-admin-password')||''}
function auth(req,res,next){const expected=process.env.ADMIN_PASSWORD||'';if(!expected)return res.status(500).json({error:'ADMIN_PASSWORD غير مضبوط في Vercel.'});if(password(req)!==expected)return res.status(401).json({error:'كلمة المرور غير صحيحة.'});next()}
async function gh(url,opt={}){const c=cfg();if(!c.token||!c.repo)throw new Error('GITHUB_TOKEN أو GITHUB_REPO غير مضبوط في Vercel.');const headers={'Accept':'application/vnd.github+json','Authorization':`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(opt.headers||{})};const r=await fetch(url,{...opt,headers});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={message:t}}if(!r.ok)throw new Error(d.message||`GitHub ${r.status}`);return d}
function norm(p){const images=Array.isArray(p.images)?p.images.map(String).filter(Boolean):(p.image?[String(p.image)]:[]);return {...p,id:String(p.id||crypto.randomUUID()),name:String(p.name||'سيارة'),price:Number(p.price)||0,year:String(p.year||''),category:String(p.category||'other'),transmission:String(p.transmission||''),fuel:String(p.fuel||''),mileage:String(p.mileage||''),color:String(p.color||''),description:String(p.description||''),status:p.status==='sold'?'sold':'available',images,image:images[0]||''}}
async function readProducts(){const c=cfg();const d=await gh(`${GH}/repos/${c.repo}/contents/${c.path}?ref=${encodeURIComponent(c.branch)}`);const text=Buffer.from(String(d.content).replace(/\n/g,''),'base64').toString('utf8');const data=JSON.parse(text);if(!Array.isArray(data))throw new Error('data/products.json ليس Array صالح.');return data.map(norm)}
async function writeProducts(products,message){const c=cfg();let sha;try{sha=(await gh(`${GH}/repos/${c.repo}/contents/${c.path}?ref=${encodeURIComponent(c.branch)}`)).sha}catch{}const content=Buffer.from(JSON.stringify(products,null,2)+'\n','utf8').toString('base64');const body={message,content,branch:c.branch};if(sha)body.sha=sha;await gh(`${GH}/repos/${c.repo}/contents/${c.path}`,{method:'PUT',body:JSON.stringify(body)})}
function rawUrl(path){const c=cfg();return `https://raw.githubusercontent.com/${c.repo}/${c.branch}/${path}`}
async function uploadOne(file){const c=cfg();const ext=(file.originalname.match(/\.[a-z0-9]+$/i)||['.jpg'])[0].toLowerCase();const allowed=['.jpg','.jpeg','.png','.webp','.gif'];const e=allowed.includes(ext)?ext:'.jpg';const base=(file.originalname||'image').replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,45)||'image';const path=`uploads/${Date.now()}-${crypto.randomBytes(4).toString('hex')}-${base}${e}`;await gh(`${GH}/repos/${c.repo}/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Upload image ${path}`,content:file.buffer.toString('base64'),branch:c.branch})});return rawUrl(path)}
function clean(body,old={}){const images=Array.isArray(body.images)?body.images.map(String).map(s=>s.trim()).filter(Boolean):String(body.images||'').split(/\n|,/).map(s=>s.trim()).filter(Boolean);const fallback=String(body.image||old.image||'').trim();const imgs=images.length?images:(old.images||[]).filter(Boolean);if(!imgs.length&&fallback)imgs.push(fallback);const name=String(body.name??old.name??'').trim();if(!name)throw new Error('اسم السيارة مطلوب.');const price=Number(body.price??old.price??0);if(!Number.isFinite(price)||price<0)throw new Error('السعر غير صحيح.');return norm({id:String(body.id??old.id??crypto.randomUUID()),name,price,year:String(body.year??old.year??''),category:String(body.category??old.category??'other'),transmission:String(body.transmission??old.transmission??''),fuel:String(body.fuel??old.fuel??''),mileage:String(body.mileage??old.mileage??''),color:String(body.color??old.color??''),description:String(body.description??old.description??''),status:body.status??old.status??'available',images:imgs,image:imgs[0]||fallback})}
const fail=(res,e)=>res.status(500).json({error:e.message||'حدث خطأ'});
app.get(['/api/health','/health'],(req,res)=>res.json({ok:true,service:'automobile-elkheshen',time:new Date().toISOString()}));
app.get(['/api/products','/products'],async(req,res)=>{try{res.json(await readProducts())}catch(e){fail(res,e)}});
app.get(['/api/admin/products','/admin/products'],auth,async(req,res)=>{try{res.json(await readProducts())}catch(e){fail(res,e)}});
app.post(['/api/admin/upload-images','/admin/upload-images'],auth,upload.array('images',12),async(req,res)=>{try{const files=req.files||[];if(!files.length)return res.status(400).json({error:'اختر صورة واحدة على الأقل.'});const allowed=['image/jpeg','image/png','image/webp','image/gif'];for(const f of files)if(!allowed.includes(f.mimetype))return res.status(400).json({error:'مسموح JPG وPNG وWEBP وGIF فقط.'});const urls=[];for(const f of files)urls.push(await uploadOne(f));res.json({ok:true,urls})}catch(e){fail(res,e)}});
app.post(['/api/admin/products','/admin/products'],auth,async(req,res)=>{try{const ps=await readProducts();const p=clean(req.body);if(ps.some(x=>x.id===p.id))return res.status(409).json({error:'معرّف السيارة مستخدم بالفعل.'});ps.push(p);await writeProducts(ps,`Add car ${p.name}`);res.json({ok:true,product:p})}catch(e){fail(res,e)}});
app.put(['/api/admin/products/:id','/admin/products/:id'],auth,async(req,res)=>{try{const ps=await readProducts();const i=ps.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'السيارة غير موجودة.'});const p=clean({...req.body,id:req.params.id},ps[i]);ps[i]=p;await writeProducts(ps,`Update car ${p.name}`);res.json({ok:true,product:p})}catch(e){fail(res,e)}});
app.delete(['/api/admin/products/:id','/admin/products/:id'],auth,async(req,res)=>{try{const ps=await readProducts();const next=ps.filter(x=>x.id!==req.params.id);if(next.length===ps.length)return res.status(404).json({error:'السيارة غير موجودة.'});await writeProducts(next,`Delete car ${req.params.id}`);res.json({ok:true})}catch(e){fail(res,e)}});
app.post(['/api/order','/order'],(req,res)=>res.json({ok:true,orderId:`AE-${Date.now().toString().slice(-8)}`}));
module.exports=app;
